/**
 * Demo leads used as fallback when the production DB has no data yet.
 * These are realistic Phoenix, AZ commercial parking lots.
 * Replace with real scored lots once Neon DB is live.
 */

export const DEMO_LEADS = [
  {
    id: 'demo-001',
    city: 'Phoenix',
    state: 'AZ',
    market: 'phoenix_az',
    conditionScore: 9,
    urgency: 'CRITICAL',
    damageTypes: JSON.stringify(['Severe oxidation', 'Alligator cracking', 'Faded striping', 'Drainage failure']),
    estimatedJobMin: 55000,
    estimatedJobMax: 85000,
    propertyType: 'COMMERCIAL_PARKING',
    lotSqFt: 42000,
    blurredImageUrl: null,
    lat: 33.4484,
    lng: -112.0740,
    vertical: ['PAVING', 'STRIPING'],
    status: 'AVAILABLE',
    sharedBuyerCount: 1,
    maxSharedBuyers: 3,
    exclusiveBuyerId: null,
    exclusiveExpiresAt: null,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-002',
    city: 'Scottsdale',
    state: 'AZ',
    market: 'phoenix_az',
    conditionScore: 8,
    urgency: 'HIGH',
    damageTypes: JSON.stringify(['Pothole clusters', 'Oxidation', 'Line fading']),
    estimatedJobMin: 38000,
    estimatedJobMax: 62000,
    propertyType: 'RETAIL_STRIP',
    lotSqFt: 28500,
    blurredImageUrl: null,
    lat: 33.4942,
    lng: -111.9261,
    vertical: ['PAVING', 'STRIPING'],
    status: 'AVAILABLE',
    sharedBuyerCount: 0,
    maxSharedBuyers: 3,
    exclusiveBuyerId: null,
    exclusiveExpiresAt: null,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-003',
    city: 'Tempe',
    state: 'AZ',
    market: 'phoenix_az',
    conditionScore: 7,
    urgency: 'HIGH',
    damageTypes: JSON.stringify(['Longitudinal cracking', 'Surface oxidation', 'ADA non-compliant']),
    estimatedJobMin: 29000,
    estimatedJobMax: 47000,
    propertyType: 'OFFICE_PARK',
    lotSqFt: 19800,
    blurredImageUrl: null,
    lat: 33.4255,
    lng: -111.9400,
    vertical: ['PAVING'],
    status: 'AVAILABLE',
    sharedBuyerCount: 2,
    maxSharedBuyers: 3,
    exclusiveBuyerId: null,
    exclusiveExpiresAt: null,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-004',
    city: 'Chandler',
    state: 'AZ',
    market: 'phoenix_az',
    conditionScore: 9,
    urgency: 'CRITICAL',
    damageTypes: JSON.stringify(['Alligator cracking', 'Heaving', 'Faded striping', 'Oil staining']),
    estimatedJobMin: 72000,
    estimatedJobMax: 110000,
    propertyType: 'COMMERCIAL_PARKING',
    lotSqFt: 58000,
    blurredImageUrl: null,
    lat: 33.3062,
    lng: -111.8413,
    vertical: ['PAVING', 'STRIPING'],
    status: 'AVAILABLE',
    sharedBuyerCount: 0,
    maxSharedBuyers: 3,
    exclusiveBuyerId: null,
    exclusiveExpiresAt: null,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-005',
    city: 'Mesa',
    state: 'AZ',
    market: 'phoenix_az',
    conditionScore: 6,
    urgency: 'MEDIUM',
    damageTypes: JSON.stringify(['Surface cracking', 'Faded lines', 'Pothole (2)']),
    estimatedJobMin: 18000,
    estimatedJobMax: 31000,
    propertyType: 'RETAIL_STRIP',
    lotSqFt: 15200,
    blurredImageUrl: null,
    lat: 33.4152,
    lng: -111.8315,
    vertical: ['STRIPING', 'PAVING'],
    status: 'AVAILABLE',
    sharedBuyerCount: 1,
    maxSharedBuyers: 3,
    exclusiveBuyerId: null,
    exclusiveExpiresAt: null,
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-006',
    city: 'Peoria',
    state: 'AZ',
    market: 'phoenix_az',
    conditionScore: 8,
    urgency: 'HIGH',
    damageTypes: JSON.stringify(['Block cracking', 'Severe oxidation', 'Stripe obliteration']),
    estimatedJobMin: 44000,
    estimatedJobMax: 68000,
    propertyType: 'COMMERCIAL_PARKING',
    lotSqFt: 34000,
    blurredImageUrl: null,
    lat: 33.5806,
    lng: -112.2374,
    vertical: ['PAVING', 'STRIPING'],
    status: 'AVAILABLE',
    sharedBuyerCount: 0,
    maxSharedBuyers: 3,
    exclusiveBuyerId: null,
    exclusiveExpiresAt: null,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-007',
    city: 'Glendale',
    state: 'AZ',
    market: 'phoenix_az',
    conditionScore: 5,
    urgency: 'MEDIUM',
    damageTypes: JSON.stringify(['Minor cracking', 'Faded striping']),
    estimatedJobMin: 12000,
    estimatedJobMax: 22000,
    propertyType: 'MIXED_USE',
    lotSqFt: 11400,
    blurredImageUrl: null,
    lat: 33.5387,
    lng: -112.1860,
    vertical: ['STRIPING'],
    status: 'AVAILABLE',
    sharedBuyerCount: 0,
    maxSharedBuyers: 3,
    exclusiveBuyerId: null,
    exclusiveExpiresAt: null,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-008',
    city: 'Gilbert',
    state: 'AZ',
    market: 'phoenix_az',
    conditionScore: 9,
    urgency: 'CRITICAL',
    damageTypes: JSON.stringify(['Alligator cracking', 'Pothole clusters', 'Complete stripe loss', 'Curb damage']),
    estimatedJobMin: 88000,
    estimatedJobMax: 135000,
    propertyType: 'COMMERCIAL_PARKING',
    lotSqFt: 71000,
    blurredImageUrl: null,
    lat: 33.3528,
    lng: -111.7890,
    vertical: ['PAVING', 'STRIPING'],
    status: 'AVAILABLE',
    sharedBuyerCount: 0,
    maxSharedBuyers: 3,
    exclusiveBuyerId: null,
    exclusiveExpiresAt: null,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-009',
    city: 'Scottsdale',
    state: 'AZ',
    market: 'phoenix_az',
    conditionScore: 7,
    urgency: 'HIGH',
    damageTypes: JSON.stringify(['Reflective cracking', 'Oxidation', 'Faded parking lines']),
    estimatedJobMin: 31000,
    estimatedJobMax: 52000,
    propertyType: 'OFFICE_PARK',
    lotSqFt: 24600,
    blurredImageUrl: null,
    lat: 33.5620,
    lng: -111.8907,
    vertical: ['PAVING'],
    status: 'AVAILABLE',
    sharedBuyerCount: 1,
    maxSharedBuyers: 3,
    exclusiveBuyerId: null,
    exclusiveExpiresAt: null,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-010',
    city: 'Phoenix',
    state: 'AZ',
    market: 'phoenix_az',
    conditionScore: 6,
    urgency: 'MEDIUM',
    damageTypes: JSON.stringify(['Transverse cracking', 'Surface raveling', 'Faded lines']),
    estimatedJobMin: 22000,
    estimatedJobMax: 38000,
    propertyType: 'INDUSTRIAL',
    lotSqFt: 32000,
    blurredImageUrl: null,
    lat: 33.5200,
    lng: -112.0600,
    vertical: ['PAVING'],
    status: 'AVAILABLE',
    sharedBuyerCount: 0,
    maxSharedBuyers: 3,
    exclusiveBuyerId: null,
    exclusiveExpiresAt: null,
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-011',
    city: 'Tempe',
    state: 'AZ',
    market: 'phoenix_az',
    conditionScore: 8,
    urgency: 'HIGH',
    damageTypes: JSON.stringify(['Pothole field', 'Severe oxidation', 'Missing striping']),
    estimatedJobMin: 48000,
    estimatedJobMax: 74000,
    propertyType: 'RETAIL_STRIP',
    lotSqFt: 36800,
    blurredImageUrl: null,
    lat: 33.4302,
    lng: -111.9498,
    vertical: ['PAVING', 'STRIPING'],
    status: 'AVAILABLE',
    sharedBuyerCount: 2,
    maxSharedBuyers: 3,
    exclusiveBuyerId: null,
    exclusiveExpiresAt: null,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-012',
    city: 'Mesa',
    state: 'AZ',
    market: 'phoenix_az',
    conditionScore: 9,
    urgency: 'CRITICAL',
    damageTypes: JSON.stringify(['Full-depth cracking', 'Subbase failure', 'Potholes', 'Drainage blocked']),
    estimatedJobMin: 95000,
    estimatedJobMax: 148000,
    propertyType: 'COMMERCIAL_PARKING',
    lotSqFt: 83000,
    blurredImageUrl: null,
    lat: 33.4200,
    lng: -111.8100,
    vertical: ['PAVING', 'STRIPING'],
    status: 'AVAILABLE',
    sharedBuyerCount: 0,
    maxSharedBuyers: 3,
    exclusiveBuyerId: null,
    exclusiveExpiresAt: null,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export type DemoLead = (typeof DEMO_LEADS)[number];
