/**
 * Seed commercial parking lot leads into the database.
 * Reads from data/raw-lots.json (generated by fetch-lots.ts)
 * OR uses built-in sample data if file doesn't exist.
 *
 * Usage: npx tsx scripts/seed-leads.ts
 */

import { PrismaClient } from '@prisma/client';
import * as fs from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';

const db = new PrismaClient();

type RawLot = {
  osm_id?: number;
  lat: number;
  lng: number;
  market: string;
  city: string;
  state: string;
  zip: string;
  address?: string;
  name?: string;
  surface?: string;
  capacity?: number | null;
  area_approx?: number | null;
};

// Damage types per condition score bracket
const DAMAGE_BY_SCORE: Record<number, string[][]> = {
  10: [['severe alligator cracking', 'multiple potholes', 'standing water', 'base failure']],
  9: [['extensive alligator cracking', 'potholes', 'edge deterioration', 'drainage issues']],
  8: [['alligator cracking', 'raveling', 'transverse cracks', 'faded line striping']],
  7: [['longitudinal cracking', 'surface oxidation', 'edge cracking', 'patching needed']],
  6: [['transverse cracking', 'surface oxidation', 'minor raveling', 'faded striping']],
  5: [['minor cracking', 'surface oxidation', 'striping faded', 'seal coat needed']],
  4: [['hairline cracking', 'surface weathering', 'minor patching']],
  3: [['minor surface wear', 'faded striping', 'sealant needed']],
};

// Sample property manager names and contacts (realistic but fake — for demo)
const PROPERTY_MANAGERS = [
  { name: 'James Mitchell', phone: '(312) 555-0187', email: 'jmitchell@midwestproperties.com' },
  { name: 'Sandra Torres', phone: '(214) 555-0293', email: 'storres@dallaspropertygroup.com' },
  { name: 'Robert Chen', phone: '(602) 555-0341', email: 'rchen@phoenixcommercial.com' },
  { name: 'Patricia Williams', phone: '(312) 555-0412', email: 'pwilliams@lakeviewpm.com' },
  { name: 'David Johnson', phone: '(214) 555-0158', email: 'djohnson@dfw-realty.com' },
  { name: 'Karen Anderson', phone: '(602) 555-0267', email: 'kanderson@azcommercial.net' },
  { name: 'Michael Brown', phone: '(312) 555-0534', email: 'mbrown@chicagoassets.com' },
  { name: 'Lisa Martinez', phone: '(214) 555-0389', email: 'lmartinez@txproperties.com' },
  { name: 'Thomas Davis', phone: '(602) 555-0476', email: 'tdavis@sunbeltpm.com' },
  { name: 'Jennifer Wilson', phone: '(312) 555-0621', email: 'jwilson@northshore-pm.com' },
  { name: 'Christopher Lee', phone: '(214) 555-0734', email: 'clee@metrodallas.com' },
  { name: 'Amanda Taylor', phone: '(602) 555-0852', email: 'ataylor@desertproperties.com' },
  { name: 'Daniel Harris', phone: '(312) 555-0943', email: 'dharris@windy-city-pm.com' },
  { name: 'Michelle Clark', phone: '(214) 555-0167', email: 'mclark@texaspm.net' },
  { name: 'Kevin Robinson', phone: '(602) 555-0285', email: 'krobinson@arizonarealty.com' },
];

const PROPERTY_TYPES = ['COMMERCIAL_PARKING', 'RETAIL_STRIP', 'OFFICE_PARK', 'INDUSTRIAL', 'MIXED_USE'] as const;

const STREET_NAMES_BY_MARKET: Record<string, string[]> = {
  chicago_il: [
    '123 W Michigan Ave', '4520 N Harlem Ave', '2800 S Wentworth Ave',
    '6100 N Milwaukee Ave', '3400 W Irving Park Rd', '8900 S Cicero Ave',
    '1200 N Ashland Ave', '5600 W Belmont Ave', '2100 S Kedzie Ave',
    '7800 N Western Ave', '3300 W Diversey Ave', '9200 S Stony Island Ave',
    '1800 N Clark St', '4100 W Lawrence Ave', '6700 S Halsted St',
    '2500 N Western Ave', '8100 S Commercial Ave', '1500 W Devon Ave',
    '3700 N Cicero Ave', '5200 S Pulaski Rd', '7100 W Touhy Ave',
    '900 N Michigan Ave', '4800 S Kedzie Ave', '11200 S Halsted St',
    '2200 N Clybourn Ave', '6300 W Foster Ave', '8400 S Western Ave',
  ],
  dallas_tx: [
    '4800 Belt Line Rd', '12000 Inwood Rd', '3500 Oak Lawn Ave',
    '9200 Forest Ln', '6100 Greenville Ave', '2800 W Mockingbird Ln',
    '5500 Lemmon Ave', '11400 N Central Expy', '7800 Abrams Rd',
    '3200 Garland Rd', '8600 E NW Hwy', '4400 S Buckner Blvd',
    '10200 Plano Rd', '2100 W Jefferson Blvd', '7100 S Hampton Rd',
    '5900 Skillman St', '1900 N Beckley Ave', '9400 W Illinois Ave',
    '3800 S Westmoreland Rd', '6600 Military Pkwy', '13500 Preston Rd',
    '4200 W Davis St', '8000 Park Ln', '1600 N Peak St',
    '5100 Ross Ave', '11800 Harry Hines Blvd', '7500 S Lancaster Rd',
  ],
  phoenix_az: [
    '3400 W Camelback Rd', '7800 N 19th Ave', '2100 E McDowell Rd',
    '5500 W Thomas Rd', '9200 E Shea Blvd', '1800 N 7th St',
    '6300 S 16th St', '4100 W Indian School Rd', '8800 E Van Buren St',
    '3700 N 32nd St', '10500 W Peoria Ave', '2400 E Bell Rd',
    '5900 S 48th St', '7300 N 43rd Ave', '1500 W Baseline Rd',
    '4800 E Thomas Rd', '9600 W Camelback Rd', '3100 N 67th Ave',
    '6700 E McDowell Rd', '8200 S Central Ave', '2700 W Thunderbird Rd',
    '5200 N 51st Ave', '11100 E Indian Bend Rd', '4500 W Glendale Ave',
    '7000 S 7th St', '1300 E Northern Ave', '9800 W Thomas Rd',
  ],
};

function getRandomItem<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

function scoreToEstimate(score: number, sqft: number): { min: number; max: number } {
  // Commercial paving: ~$2.50–$7.00/sqft depending on work type
  const multiplier = 0.5 + (score / 10) * 0.5;
  const minPer = 2.5 * multiplier;
  const maxPer = 7.0 * multiplier;
  return {
    min: Math.round((sqft * minPer) / 1000) * 1000,
    max: Math.round((sqft * maxPer) / 1000) * 1000,
  };
}

function generateLeadFromLot(lot: RawLot, index: number) {
  // Assign a realistic condition score — weighted toward higher scores (more urgent lots are more interesting)
  const scoreWeights = [0, 0, 0.02, 0.05, 0.08, 0.12, 0.15, 0.20, 0.22, 0.10, 0.06];
  const rand = Math.random();
  let score = 5;
  let cumulative = 0;
  for (let i = 1; i <= 10; i++) {
    cumulative += scoreWeights[i] ?? 0;
    if (rand <= cumulative) { score = i; break; }
  }

  const damages = DAMAGE_BY_SCORE[score]?.[0] ?? ['surface wear', 'minor cracking'];
  const sqft = lot.area_approx && lot.area_approx > 1000
    ? Math.min(lot.area_approx, 200000)
    : Math.floor(Math.random() * 40000) + 8000;
  const estimate = scoreToEstimate(score, sqft);
  const pm = PROPERTY_MANAGERS[index % PROPERTY_MANAGERS.length];
  const streetNames = STREET_NAMES_BY_MARKET[lot.market] ?? [];
  const streetAddr = lot.address && lot.address.trim().length > 3
    ? lot.address
    : getRandomItem(streetNames) || `${Math.floor(Math.random() * 9000 + 1000)} Commerce Dr`;

  const propertyTypes = PROPERTY_TYPES;
  const propertyType = getRandomItem([...propertyTypes]);
  const verticals = score >= 6 && Math.random() > 0.4
    ? ['PAVING', 'STRIPING']
    : Math.random() > 0.3
    ? ['PAVING']
    : ['STRIPING'];

  const urgencyMap: Record<number, string> = { 10: 'CRITICAL', 9: 'CRITICAL', 8: 'HIGH', 7: 'HIGH', 6: 'MEDIUM', 5: 'MEDIUM', 4: 'LOW', 3: 'LOW' };

  return {
    address: streetAddr,
    city: lot.city || 'Chicago',
    state: lot.state || 'IL',
    zip: lot.zip || '60601',
    lat: lot.lat,
    lng: lot.lng,
    market: lot.market,
    conditionScore: score,
    damageTypes: JSON.stringify(damages),
    estimatedJobMin: estimate.min,
    estimatedJobMax: estimate.max,
    urgency: urgencyMap[score] || 'MEDIUM',
    lotSqFt: sqft,
    propertyType,
    vertical: verticals,
    status: 'AVAILABLE' as const,
    sharedBuyerCount: 0,
    maxSharedBuyers: 3,
    propertyManagerName: pm.name,
    propertyManagerEmail: pm.email,
    propertyManagerPhone: pm.phone,
    propertySource: 'assessor',
    propertyName: lot.name || null,
  };
}

async function main() {
  console.log('🚀 Starting lead database seed...\n');

  // Load raw lots if available
  const rawPath = path.join(process.cwd(), 'data', 'raw-lots.json');
  let rawLots: RawLot[] = [];

  if (fs.existsSync(rawPath)) {
    rawLots = JSON.parse(fs.readFileSync(rawPath, 'utf-8'));
    console.log(`📂 Loaded ${rawLots.length} raw lots from ${rawPath}`);
  } else {
    console.log('⚠️  No raw-lots.json found. Generating synthetic leads for all 3 markets...');
    // Generate synthetic lots spread across markets
    const markets = [
      { id: 'chicago_il', city: 'Chicago', state: 'IL', baseLat: 41.88, baseLng: -87.63 },
      { id: 'dallas_tx', city: 'Dallas', state: 'TX', baseLat: 32.78, baseLng: -96.80 },
      { id: 'phoenix_az', city: 'Phoenix', state: 'AZ', baseLat: 33.45, baseLng: -112.07 },
    ];

    for (const market of markets) {
      for (let i = 0; i < 80; i++) {
        rawLots.push({
          lat: market.baseLat + (Math.random() - 0.5) * 0.4,
          lng: market.baseLng + (Math.random() - 0.5) * 0.4,
          market: market.id,
          city: market.city,
          state: market.state,
          zip: '',
          address: '',
        });
      }
    }
    console.log(`Generated ${rawLots.length} synthetic lot coordinates`);
  }

  // Filter to high-quality lots (has lat/lng), shuffle to spread across markets
  const allValid = rawLots.filter((l) => l.lat && l.lng && Math.abs(l.lat) > 0 && Math.abs(l.lng) > 0);
  // Take proportional samples per market (up to 160 per market = 480 total)
  const marketBuckets: Record<string, typeof allValid> = {};
  for (const lot of allValid) { (marketBuckets[lot.market] = marketBuckets[lot.market] ?? []).push(lot); }
  const validLots = Object.values(marketBuckets).flatMap(lots => {
    const shuffled = lots.sort(() => Math.random() - 0.5);
    return shuffled.slice(0, 160);
  });

  console.log(`\n📊 Processing ${validLots.length} lots...`);

  // Generate lead objects
  const leads = validLots.map((lot, i) => generateLeadFromLot(lot, i));

  // Upsert in batches
  let created = 0;
  const BATCH_SIZE = 25;

  for (let i = 0; i < leads.length; i += BATCH_SIZE) {
    const batch = leads.slice(i, i + BATCH_SIZE);
    await Promise.all(
      batch.map((lead) =>
        db.lead.create({ data: lead as any }).catch((err) => {
          if (!err.message?.includes('unique')) console.error('Lead create error:', err.message);
        })
      )
    );
    created += batch.length;
    process.stdout.write(`\r  Progress: ${Math.min(created, leads.length)}/${leads.length}`);
  }

  console.log(`\n\n✅ Seeded ${leads.length} leads`);

  // Print breakdown
  const byMarket = leads.reduce((acc, l) => {
    acc[l.market] = (acc[l.market] ?? 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  console.log('\nBreakdown by market:');
  for (const [market, count] of Object.entries(byMarket)) {
    console.log(`  ${market}: ${count} leads`);
  }

  const byScore = leads.reduce((acc, l) => {
    const key = l.conditionScore >= 8 ? 'Critical (8-10)' : l.conditionScore >= 6 ? 'High (6-7)' : 'Moderate (3-5)';
    acc[key] = (acc[key] ?? 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  console.log('\nBreakdown by urgency:');
  for (const [urgency, count] of Object.entries(byScore)) {
    console.log(`  ${urgency}: ${count} leads`);
  }

  await db.$disconnect();
}

main().catch(async (e) => {
  console.error(e);
  await db.$disconnect();
  process.exit(1);
});
